### ISSUE TITLE
Review the list of tags

### ISSUE THREAD

**Issue by alranel** [italia/publiccode.yml#28]
As of now, the [list of allowed values](https://github.com/italia/publiccode.yml/blob/master/docs/it/tags.rst) for the `tags` key is not very comprehensive and government-oriented, and it mixes two distinct ontologies:

* what the software _is_
* what the software _is used for_

There's `backend` but there's no `mobile app` or `website` or `web application`.
There are `amusement` and `instant-messaging` but there's no `culture` or `cultural heritage` or `human resources management` or `time tracking` or `open data` or `gis` or many other categories of public software.

**Comment by alranel** [comment]
Proposal:

* remove `freeTags` as it will end up messy (multiple languages etc.);
* keep `softwareType` for standalone/addon/library/etc.
* add `category` for desktop/mobile/cloud/website/webapplication/gateway/etc.
* add `scope` for healthcare/education/accounting/etc.

**Comment by libremente** [comment]
Fixed by #45. Closing.
