### ISSUE TITLE
Relative vs absolute URLs

### ISSUE THREAD

**Issue by alranel** [italia/publiccode.yml#32]
Some fields expect relative paths to files contained in the repository. For example `description/[lang]/screenshots` and `legal/authorsFile`. It should be clearly stated that those fields are expected to contain either:

* a relative path to a file contained in the repository (relative to the publiccode.yml file, thus to the repository root)
* an absolute URL pointing to the raw file, but only if the file is contained in the same repository as the publiccode.yml file itself

This limitation ensures that the file is owned by the software publisher, or published under an open license, so that there's no potential issue in embedding it in a catalog.

**Comment by libremente** [comment]
This PR #33 solves this issue. Closing.
