### ISSUE TITLE
Independent versioning for country-specific extensions?

### ISSUE THREAD

**Issue by alranel** [italia/publiccode.yml#39]
As of now, every update to fields defined in a country-specific extension (for instance `it/riuso/codiceIPA`) would require to increment the `publiccodeYmlVersion` field.

While this is semantically correct, it triggers unneeded extra work by all implementers. Whenever a country makes an update to its extension, all the parsers need to be updated in order to accept the newer version number even if they are not affected by the change.

We should consider adding a version field to each country extension, and _not_ increment `publiccodeYmlVersion` when country extensions are updated. This way, each parser can update the list of versions it supports only if it is affected by the change (i.e. if the change affects the common part _or_ a country-specific extension it supports).

**Comment by alranel** [comment]
A drawback of this approach is that this make using tags and releases complicated, if not unfeasible, if we want to keep everything in a single repository.

**Comment by alranel** [comment]
Proposal: let's tag every update to the core and/or to a country-specific extension, with a tag that combines both:

* core:0.2/it:0.4
* core:0.2/fr:1.1
* ...

We can add a `version` (?) key to the country-specific section:

```
it:
   version: 0.4
   riuso:
      codiceIPA: c_bac
```

**Comment by libremente** [comment]
> Proposal: let's tag every update to the core and/or to a country-specific extension, with a tag that combines both:
> 
>     * core:0.2/it:0.4
> 
>     * core:0.2/fr:1.1

Sounds good to me. :+1: 

> 
> We can add a `version` (?) key to the country-specific section:
> 
> ```
> it:
>    version: 0.4
>    riuso:
>       codiceIPA: c_bac
> ```
Also this one is reasonable.
Proposal: may we call it something like 
* `publiccodeYmlExtensionVersion`
* `publiccodeYmlCountryVersion`
* `publiccodeYmlCountryExtensionVersion`
* `publiccodeYmlCountryExtVersion`

for coherence with the primary `publiccodeYmlVersion`?

**Comment by libremente** [comment]
Selected `CountryExtensionVersion`.

**Comment by libremente** [comment]
Fixed by #47. Closing.
