### ISSUE TITLE
Review publiccode

### ISSUE THREAD

**Issue by ioggstream** [italia/publiccode.yml#4]
A list of questions:

 - [x]  Spinal-case or camelCase?
https://github.com/italia/publiccode.yml/blob/master/version/development/example/publiccode.yml#L1 
 -  [ ] Consider `summary` and `description` or avoid `dict["description"]["*description"]`
https://github.com/italia/publiccode.yml/blob/master/version/development/example/publiccode.yml#L54
- [ ] Always use `url` instead of `website` or other synonims. 
https://github.com/italia/publiccode.yml/blob/master/version/development/example/publiccode.yml#L95
-  [ ] Why is that? https://github.com/italia/publiccode.yml/blob/master/version/development/example/publiccode.yml#L14
-  [ ] Potentially long https://github.com/italia/publiccode.yml/blob/master/version/development/example/publiccode.yml#L29
-  [ ] Why Countries? https://github.com/italia/publiccode.yml/blob/master/version/development/example/publiccode.yml#L44
-  [x] Use plurals eg `features` not datatypes
https://github.com/italia/publiccode.yml/blob/master/version/development/example/publiccode.yml#L70
-  [ ] `name, url, email` everywhere
https://github.com/italia/publiccode.yml/blob/master/version/development/example/publiccode.yml#L95
- [ ] Here's `Diego "Zoro" Bianchi`
https://github.com/italia/publiccode.yml/blob/master/version/development/example/publiccode.yml#L104
- [ ] bcp47
https://github.com/italia/publiccode.yml/blob/master/version/development/example/publiccode.yml#L116
- [ ] still open point as there are big entities (eg. AdE) under a single IPA entity
https://github.com/italia/publiccode.yml/blob/master/version/development/example/publiccode.yml#L148

**Comment by alranel** [comment]
All these things were evalated. Some were implemented. BCP47 was moved to a separate issue (#2).
