### ISSUE TITLE
Updates to the Italian section

### ISSUE THREAD

**Issue by alranel** [italia/publiccode.yml#48]
* As of #45 we have a new core `scope` key which basically matches the ontology represented by our `it/riuso/ecosistemi`. Thus we can remove `it/riuso/ecosistemi`.

* Change `conforme/accessibile` to `conforme/linee-guida-design`

* Change `conforme/interoperabile` to `conforme/modello-interoperabilita`

* Change `conforme/sicuro` to `conforme/misure-minime-sicurezza`

* Change `conforme/privacy` to `conforme/gdpr`

* Move `spid`, `cie`, `anpr`, `pagopa` under a new `piattaforme` section

**Comment by alranel** [comment]
Also:

* Remove `designKit` (we can more effectively detect whether Bootstrap Italia or the web toolkit are used by having the crawler inspect the repository contents)

**Comment by libremente** [comment]
Fixed by #50. Closing.
