### ISSUE TITLE
Consider to change softwareVersion not static

### ISSUE THREAD

**Issue by mspasiano** [italia/publiccode.yml#64]
Now the software version is static, it could alternatively indicate a URL, or for the artifacts present on maven central it would be enough to indicate the groupId and the artifactId

**Comment by alranel** [comment]
In that case, any crawler or parser would need to implement custom API calls to retrieve the version from all potential backends, and there's no standard format for that...

**Comment by mspasiano** [comment]
ok ... I found a different solution described in the repository
https://github.com/mspasiano/publiccode-maven

**Comment by libremente** [comment]
Hi @mspasiano, should we consider this issue as resolved? Thanks!

**Comment by mspasiano** [comment]
Yes you can close it. Thanks.
