### ISSUE TITLE
Boolean fields values should be true or false

### ISSUE THREAD

**Issue by Lorezz** [italia/publiccode.yml#8]
Instead of `'yes'`  boolean type should be `true` or `false`

**Comment by libremente** [comment]
A Boolean represents a true/false value. Booleans are formatted as English words (“true”/“false”, “yes”/“no” or “on”/“off”) for readability and may be abbreviated as a single character “y”/“n” or “Y”/“N”. 
source: https://yaml.org/type/bool.html

**Comment by libremente** [comment]
Since the YAML format is thought for readability, I believe that `yes/no` format is preferred. As such, I'm closing this issue.

**Comment by libremente** [comment]
Reopening since YAML 1.3 deprecates yes/no

**Comment by libremente** [comment]
Merged in development #56.
